name: Strava Metrics Push

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

jobs:
  push_metrics:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install prometheus-remote-writer

    - name: Run Strava push script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        CODE: ${{ secrets.CODE }}
        REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        GRAFANA_USER_ID: ${{ secrets.GRAFANA_USER_ID }}
        GRAFANA_API_KEY: ${{ secrets.GRAFANA_API_KEY }}
        GRAFANA_PROM_URL: ${{ secrets.GRAFANA_PROM_URL }}
        ENV: PROD
        UPSTASH_REDIS_REST_URL: ${{ secrets.UPSTASH_REDIS_REST_URL }}
        UPSTASH_REDIS_REST_TOKEN: ${{ secrets.UPSTASH_REDIS_REST_TOKEN }}
      run: |
        python strava.py
        echo "Strava metrics pushed at $(date)"
